### PR TITLE
Update to latest dependencies (March 7th, 2018)

### PR DESCRIPTION
**Pull request by shirakaba**

### CODE REVIEW

**Comment by cbrevik** [comment]
Thanks for the PR! How did you do the `react-native` upgrade? Weren't there native project changes + potentially other things between 0.45 & 0.54?

**Comment by shirakaba** [comment]
> Weren't there native project changes + potentially other things between 0.45 & 0.54?

I wasn't aware (just starting out here). After a simple `npm install` of all the latest dependencies, the project ran without complaint in iOS simulator for me. Is there anything I should look out for?

Note: I'd hold fire on accepting this pull request for a moment; I had it running yesterday, but it's not working anymore today. Maybe when I got it running, it was on the old version, or on cache – anyway, I need to investigate this.

**Comment by cbrevik** [comment]
That's okay, I just did an upgrade myself. Check newest master 👍

**Comment by cbrevik** [comment]
As a general tip, when upgrading React Native versions I recommend using `react-native-git-upgrade`. It will also do native project upgrades + other stuff

**Pull request closed without merging**
